### PR TITLE
chore(nginx): add Tobias Stadler as codeowner

### PR DESCRIPTION
**Pull request by seemk**
He has been doing most of the PRs as of late and help is greatly appreciated :slightly_smiling_face: 

See: https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/144#issuecomment-1099928226

### CODE REVIEW

**Review by lalitb — APPROVED** [review]

**Comment by seemk** [comment]
@tobiasstadler Are you willing to create a membership request to the OpenTelemetry community repo? You need to be a member before you can be added to cpp-contrib-approvers. E.g. similar to https://github.com/open-telemetry/community/issues/699

**Comment by tobiasstadler** [comment]
@seemk The PR template says I need two sponsors for membership request. I suppose you are one of them? Do you know who could be the other one?

**Comment by seemk** [comment]
> @seemk The PR template says I need two sponsors for membership request. I suppose you are one of them? Do you know who could be the other one?

@lalitb perhaps?

**Comment by tobiasstadler** [comment]
@lalitb Are you willing to sponsor me?

**Comment by lalitb** [comment]
> @lalitb Are you willing to sponsor me?

Yes sure.

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
