### PR TITLE
feat(nginx): opentelemetry v1.3.0

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by seemk** [comment]
Thanks! Would you be up to help co-maintain this project? I'm a bit in need of extra time and would definitely like some help :slightly_smiling_face:

**Review by seemk — APPROVED** [review]

**Comment by tobiasstadler** [comment]
Sure, I would like todo that.

**Comment by seemk** [comment]
> Sure, I would like todo that.

Thanks, I've asked how to do it in the cpp slack

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
