### PR TITLE
nginx: link the module against libstd++ and the (used) opentelemetry libraries in the nginx build

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by seemk** [comment]
Thanks, are these libraries enough? See the discussion at https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/52

**Comment by tobiasstadler** [comment]
Yes, I think so. At least it is working for me that way (building opentelemtry as shared libraries)

**Comment by tobiasstadler** [comment]
If (for other use cases) there is something missing we can still add it later

**Review by seemk — APPROVED** [review]

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
