### PR TITLE
Add support for B3Multi headers propagation

### PR DESCRIPTION
**Pull request by kuzaxak**
Some services expect [B3 Multi][1] headers as input information.
To support that we need to be able to Inject them into upstream requests.

Tests will be added as a separate commit later on.

Solving https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/36

[1]: https://github.com/openzipkin/b3-propagation#multiple-headers

### CODE REVIEW

**Comment by indrekj** [comment]
any chances of getting this reviewed/merged? @open-telemetry/cpp-contrib-approvers

**Comment by ThomsonTan** [comment]
@seemk could you please take a look?

**Comment by fredzach** [comment]
Hoping for updates on this, as it's currently forcing us to use opentracing for the time being.

**Comment by seemk** [comment]
Since it has been a while, I've resurrected this PR at https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/495 

Retained your original commits and added a few tests. Closing this one for now, thanks!

**Pull request closed without merging**
