### PR TITLE
Added option to globally ignore paths from beeing traced

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Review by seemk — APPROVED** [review]
Thanks! Could you perhaps add an example config line to the README section as well? :slightly_smiling_face:

**Comment by tobiasstadler** [comment]
There is an example in instrumentation/nginx/test/conf/nginx.conf which is linked from the `Usage` section in the README. Should I also add it to the sample nginx.conf in the `Usage` section?

**Comment by seemk** [comment]
> There is an example in instrumentation/nginx/test/conf/nginx.conf which is linked from the `Usage` section in the README. Should I also add it to the sample nginx.conf in the `Usage` section?

Ah no, all good then :+1:

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
