### PR TITLE
fix(nginx): Fix segfault in GetTraceContext

### PR DESCRIPTION
**Pull request by tobiasstadler**
We are seeing a segfault in `GetTraceContext(ngx_http_request_s*)` when some requests are not traced. This PR should fix it.

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@rcjsuen I changed an existing test to catch the segfault

**Comment by rcjsuen** [comment]
@tobiasstadler Thank you for your explanation and again, thank you for looking at these crashes!

**Review by seemk — APPROVED** [review]

**Comment by seemk** [comment]
Thanks!

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
