### PR TITLE
Fix worker process death in internal requests and 301's

### PR DESCRIPTION
**Pull request by Symbianx**
This PR fixes the core dumps described in #105.

With the following location, a request to `/analytics` triggers a redirect (301) to `/analytics/`. This happens at an earlier nginx processing phase, hence the null check on the map.
The same seems to happen for internal requests.

```nginx
location /analytics/ {
	opentelemetry_operation_name analytics;
	opentelemetry_propagate;
	add_header X-API-Correlation-Id $opentelemetry_trace_id always;
	
	proxy_pass http://nginx-2;
}
```

Also reduces the log level of messages when the Trace Context is not found since this is expected behaviour on this occasion.

### CODE REVIEW

**Comment by Symbianx** [comment]
After running the tests realized changing the phase breaks some tests. Converted the PR to draft for now

**Comment by rcjsuen** [comment]
@Symbianx Just wanted to say thank you for looking at this problem!

**Comment by Symbianx** [comment]
Realized I was overcomplicating by removing the whole logic with the map. This fixes the coredump on the 301 redirect.

**Comment by Symbianx** [comment]
@DebajitDas Sorry for the blunt tag but I've seen you very active on this repo.
Would it be possible to run the workflows for this PR?

**Comment by DebajitDas** [comment]
> @DebajitDas Sorry for the blunt tag but I've seen you are very active on this repo. Would it be possible to run the workflows for this PR?

@Symbianx I am the maintainer and approver of 'instrumentation/otel-webserver-module' but I am active for 'instrumentation/nginx' folder. Hope this clears your query. Also I see your workflows are run

**Comment by Symbianx** [comment]
@seemk @tobiasstadler Any chance one of you could look at this PR?

**Review by seemk — APPROVED** [review]

**Comment by seemk** [comment]
Fixing the CI here: https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/194 will merge after

**Comment by seemk** [comment]
Could you bring in the changes from main please? I tried retriggering the CI, but it still runs on `21.04` which I've removed

**Comment by Symbianx** [comment]
@seemk Merged main in my branch 👍

**Comment by seemk** [comment]
Thanks for the fix! :pray:

**Pull request merged**
